import { homeCopy } from "./home.js";
import { exploreCopy } from "./explore.js";
import { copy, type Locale } from "./i18n.js";

export const english = {
  ...copy.en,
  ...homeCopy.en,
  ...exploreCopy.en,
  "docs.kicker": "Local installation · explicit boundaries",
  "docs.lead": "Run the real inspector on your own machine. The public website explains the workflow; it never receives configuration.",
  "docs.startKicker": "Five-minute start",
  "docs.startTitle": "Build from source",
  "docs.startBody": "HarnessScope currently requires Go 1.24 or newer. Clone the repository, build one local binary, then open the authenticated loopback dashboard.",
  "docs.terminalLabel": "Terminal commands",
  "docs.sourceLabel": "source",
  "docs.scanOnly": "Prefer the terminal? Run a scan without writing a report:",
  "docs.releaseKicker": "Release state",
  "docs.releaseTitle": "No tagged binary release is published yet.",
  "docs.releaseBody": "Source, tests and candidate archives are public, but the reviewed Linux visual baseline gate remains open. GitHub Releases is informational until that gate closes and a tagged workflow succeeds.",
  "docs.releases": "GitHub Releases",
  "docs.tiersKicker": "Compatibility",
  "docs.tiersTitle": "Evidence tiers, not promises.",
  "docs.tiersCaption": "Current adapter boundaries",
  "docs.client": "Client",
  "docs.tier": "Tier",
  "docs.version": "Version / boundary",
  "docs.codexBoundary": "Exact ruleset verified for 0.162.0-alpha.2. Other versions are marked compatibility unknown.",
  "docs.claudeBoundary": "Exact ruleset verified for 2.1.259. Other versions are marked compatibility unknown.",
  "docs.cursorBoundary": "Documented local Rules and MCP sources. Effective precedence is not confirmed.",
  "docs.opencodeBoundary": "Documented local JSON/JSONC and instruction sources. Remote configuration is not fetched; effective merge precedence is not asserted.",
  "docs.localKicker": "Operating boundary",
  "docs.localTitle": "Local and offline",
  "docs.localBody": "The server binds only to 127.0.0.1 and uses a one-time authenticated launch URL. Scans, reports, snapshots, backups and rollback stay on the machine. There is no telemetry, hosted scanner or background monitor.",
  "docs.safeTitle": "Preview before change",
  "docs.safeBody": "Fix is dry-run by default. Only explicitly selected SAFE plans can be applied; source hashes, local backups, rescan verification and automatic rollback bound the operation.",
  "docs.privacyTitle": "Redaction has limits",
  "docs.privacyBody": "Credential-shaped values are redacted after parsing and paths are normalized for reports. No detector can recognize every proprietary secret, so review any report or diagnostic ZIP before sharing it.",
  "docs.linksKicker": "Authoritative references",
  "docs.linksTitle": "Read the evidence.",
  "docs.architecture": "Architecture",
  "docs.security": "Security policy",
  "docs.contributing": "Contributing",
  "docs.englishReadme": "English overview",
  "docs.chineseReadme": "中文说明",
} as const;

export type ContentKey = keyof typeof english;

const chinese: Record<ContentKey, string> = {
  ...copy["zh-CN"],
  ...homeCopy["zh-CN"],
  ...exploreCopy["zh-CN"],
  "docs.kicker": "本地安装 · 明确边界",
  "docs.lead": "在自己的计算机上运行真实检查器。公开网站只说明工作流，不接收任何配置。",
  "docs.startKicker": "五分钟开始",
  "docs.startTitle": "从源码构建",
  "docs.startBody": "HarnessScope 当前需要 Go 1.24 或更高版本。克隆仓库、构建一个本地二进制，然后打开经过认证的回环地址仪表盘。",
  "docs.terminalLabel": "终端命令",
  "docs.sourceLabel": "源码",
  "docs.scanOnly": "更喜欢终端？可直接扫描且不写入报告：",
  "docs.releaseKicker": "发布状态",
  "docs.releaseTitle": "目前尚未发布带标签的正式二进制版本。",
  "docs.releaseBody": "源码、测试和候选归档已经公开，但经过人工审阅的 Linux 视觉基线门禁仍未关闭。在门禁关闭且带标签工作流成功前，GitHub Releases 仅作为信息入口。",
  "docs.releases": "GitHub Releases",
  "docs.tiersKicker": "兼容性",
  "docs.tiersTitle": "证据等级，不是兼容承诺。",
  "docs.tiersCaption": "当前适配器边界",
  "docs.client": "客户端",
  "docs.tier": "等级",
  "docs.version": "版本与边界",
  "docs.codexBoundary": "规则集已精确验证 0.162.0-alpha.2；其他版本标记为兼容性未知。",
  "docs.claudeBoundary": "规则集已精确验证 2.1.259；其他版本标记为兼容性未知。",
  "docs.cursorBoundary": "检查文档化的本地 Rules 与 MCP 来源，不声称确定的有效优先级。",
  "docs.opencodeBoundary": "检查文档化的本地 JSON/JSONC 与指令来源；不获取远程配置，不声称确定的合并优先级。",
  "docs.localKicker": "运行边界",
  "docs.localTitle": "本地离线运行",
  "docs.localBody": "服务只监听 127.0.0.1，并使用一次性认证启动地址。扫描、报告、快照、备份和回滚都留在本机；没有遥测、托管扫描器或后台监控。",
  "docs.safeTitle": "修改前先预览",
  "docs.safeBody": "修复默认只做预览。只有明确选择的 SAFE 计划可以应用；源文件哈希、本地备份、重扫验证和自动回滚共同限制修改范围。",
  "docs.privacyTitle": "脱敏并非万能",
  "docs.privacyBody": "凭据形态的值会在解析后脱敏，报告中的路径也会规范化。任何检测器都无法识别全部专有秘密，分享报告或诊断 ZIP 前仍需人工检查。",
  "docs.linksKicker": "权威资料",
  "docs.linksTitle": "查看证据。",
  "docs.architecture": "架构文档",
  "docs.security": "安全策略",
  "docs.contributing": "贡献指南",
  "docs.englishReadme": "英文概览",
  "docs.chineseReadme": "完整中文说明",
};

export const content: Record<Locale, Record<ContentKey, string>> = { en: english, "zh-CN": chinese };
